/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import org.junit.jupiter.api.Test;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;
import java.lang.reflect.Type;
import java.util.List;
import java.util.Random;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    public static void main(String[] args) {

    }
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void GSONTest() throws FileNotFoundException {
        Gson gson = new Gson();
        Reader jsonReader = new FileReader("../recentquotes.json");

        Type quote = new TypeToken<List<Books>>() {
        }.getType();
        List<Books> quotes = new Gson().fromJson(jsonReader, quote);

        Random random = new Random();
        int randomQuote = random.nextInt(quotes.size());
        String str = ("Books{author='" + quotes.get(randomQuote).getAuthor() + "', text='"
                + quotes.get(randomQuote).getText() + "', likes=" + quotes.get(randomQuote).getLikes() + "}")
                        .toString();

        assertEquals(str, quotes.get(randomQuote).toString());
    }
}