/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
// import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;

import java.io.*;
import java.lang.reflect.Type;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws FileNotFoundException {

        Reader jsonReader = new FileReader("recentquotes.json");

        Type quote = new TypeToken<List<Books>>() {
        }.getType();
        List<Books> quotes = new Gson().fromJson(jsonReader, quote);
        int randomQuote = (int) (Math.random() * (quotes.size()));

        System.out.println(quotes.get(randomQuote));
        System.out.println("Author: " + quotes.get(randomQuote).getAuthor());
        System.out.println("Quote: " + quotes.get(randomQuote).getText());
        System.out.println("likes: " + quotes.get(randomQuote).getLikes());

    }

}